# Generated by Django 5.1.2 on 2025-03-16 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin_fichier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_hassaniya', models.CharField(max_length=255)),
                ('transliteration', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Modérateur', 'Modérateur'), ('Contributeur', 'Contributeur')], default='Contributeur', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('mot_de_passe', models.CharField(max_length=128, verbose_name='Mot de passe')),
            ],
        ),
        migrations.CreateModel(
            name='MotExtrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('À examiner', 'À examiner'), ('Confirmé', 'Confirmé')], default='À examiner', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mots_extraits', to='dictionnaire.document')),
                ('mot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mots_extraits', to='dictionnaire.mot')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='ajoute_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dictionnaire.utilisateur'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=255)),
                ('transliteration', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField()),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('valide', 'Valide')], default='en attente', max_length=20)),
                ('id_contribiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_contributor', to='dictionnaire.utilisateur')),
                ('id_moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_moderator', to='dictionnaire.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('id_contributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_contributor', to='dictionnaire.utilisateur')),
                ('id_moderateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_moderator', to='dictionnaire.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Pluriel', 'Pluriel'), ('Conjugaison', 'Conjugaison'), ('Dérivation', 'Dérivation')], max_length=20)),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='dictionnaire.mot')),
            ],
        ),
    ]
