# Generated by Django 5.1.7 on 2025-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HassaniyaWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=255, unique=True, verbose_name='Mot Hassaniya')),
                ('traduction_arabe', models.TextField(blank=True, null=True, verbose_name='Traduction en Arabe')),
                ('traduction_francais', models.TextField(blank=True, null=True, verbose_name='Traduction en Français')),
                ('derives', models.TextField(blank=True, null=True, verbose_name='Dérivés')),
                ('grammaire', models.TextField(blank=True, null=True, verbose_name='Grammaire')),
            ],
        ),
    ]
