# Generated by Django 5.1.2 on 2025-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionMot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=255)),
                ('variation_generee', models.CharField(max_length=255, verbose_name='Variation générée')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepté', 'Accepté'), ('rejeté', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Suggestion de mot',
                'verbose_name_plural': 'Suggestions de mots',
            },
        ),
    ]
